dist: focal
language: python
cache:
- pip
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
# workaround for https://travis-ci.community/t/add-python-3-10/12220/12
- '3.10.1'
before_install:
- pip install -U pip
- pip install -U setuptools
- pip install -U wheel
install:
- pip install tox-travis .[devel]
script:
- tox
